name: Run pytest and check test results

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Set up Firefox WebDriver
        run: |
          LATEST_GECKODRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
          curl -LO "https://github.com/mozilla/geckodriver/releases/download/$LATEST_GECKODRIVER_VERSION/geckodriver-$LATEST_GECKODRIVER_VERSION-linux64.tar.gz"
          tar -xzf "geckodriver-$LATEST_GECKODRIVER_VERSION-linux64.tar.gz"
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/
      - name: Set up Chrome WebDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -O https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run pytest with Chrome
        run: |
          pytest --headless --driver Chrome Part2.py
  

      - name: Check test results
        run: |
          pytest_exit_code=$?
          test_count=$(pytest --collect-only | grep "collected" | awk '{print $2}')
          passed_count=$(pytest --collect-only | grep "collected" | awk '{print $6}')
          failed_count=$((test_count - passed_count))
          echo "Total tests: $test_count"
          echo "Tests passed: $passed_count"
          echo "Tests failed: $failed_count"
          if [ $failed_count -gt 0 ]; then
            exit 1
          fi
