name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Installing package list
        run: apt list --installed    
      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: install packages
        run: pip install -r requirements.txt
      - name: Install xvfb
        run: sudo apt-get install xvfb


      - name: Run pytest with Chrome
        run: |
          pytest Part2.py
  

      - name: Check test results
        run: |
          pytest_exit_code=$?
          test_count=$(pytest --collect-only | grep "collected" | awk '{print $2}')
          passed_count=$(pytest --collect-only | grep "collected" | awk '{print $6}')
          failed_count=$((test_count - passed_count))
          echo "Total tests: $test_count"
          echo "Tests passed: $passed_count"
          echo "Tests failed: $failed_count"
          if [ $failed_count -gt 0 ]; then
            exit 1
          fi
